# Generated by Django 4.0.1 on 2022-04-18 06:14

from django.db import migrations, models
import pandas.core.tools.datetimes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARTICLE',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateField(default=pandas.core.tools.datetimes.to_datetime)),
                ('image', models.FileField(null=True, upload_to='%Y/%m/%d')),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BOARD',
            fields=[
                ('board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('date', models.DateField(default=pandas.core.tools.datetimes.to_datetime)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LOG',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_score', models.IntegerField()),
                ('feedback', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='%Y/%m/%d')),
                ('prior_tag', models.TextField()),
                ('after_tag', models.TextField()),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_day', models.IntegerField()),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone_num', models.CharField(max_length=20, null=True)),
                ('usage_count', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
